use_frameworks!

target 'ZWKeyboard_Example' do
  pod 'ZWKeyboard', :path => '../'

  target 'ZWKeyboard_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
